/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calc_prog_1(char *host, int x, int y)
{
	CLIENT *clnt;
	int  *result_1;
	operands  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROG, CALC_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	add_1_arg.x = x;
	add_1_arg.y = y;
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("A soma de x + y = %d\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc != 4) {
		printf ("usage: %s server_host NUMBER_1 NUMBER_2\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int x = atoi(argv[2]);
	int y = atoi(argv[3]);
	calc_prog_1 (host, x, y);
exit (0);
}
